### ISSUE TITLE
OpenWatcom support

### ISSUE THREAD

**Issue by adienakhmad** [iris-edu/mseedindex#2]
As I understand from [one of the commits on mseed Inspector](https://github.com/iris-edu/msi/commit/fb987a2a717d7427a9b082a379f8dbe7afc748de), the support for Windows build is dropped because of unsupported `regex.h`

I've tried to compile this project on Linux by omitting `index.h` and it still compiled without errors.

Does that mean this project may compile using OpenWatcom under Windows?

I cannot try it myself since I have no knowledge of creating OpenWatcom makefile nor compiler options for that matter.

**Comment by chad-earthscope** [comment]
I think regex.h is a relic in this code base and is not needed.  I will remove it in the next release.

Even with this change I do not plan on adding Open Watcom "wmake" files to this project.  Open Watcom has not had any changes since 2010 and it does not appear to be active.  As an alternative I would suggest looking at [Cywin](https://www.cygwin.com/) to build and run command line, unix-oriented tools like `mseedindex`.  Bear in mind that I have not tested on Cygwin, but I'm guessing it will work.

**Comment by adienakhmad** [comment]
Thanks for the suggestion Chad, 

I have had success compiling on both cygwin and [Windows Subsystem for Linux (WSL)
](https://docs.microsoft.com/en-us/windows/wsl/install-win10)

As for anyone who's also looking to use this on Windows, there are caveats on both approach.

**cygwin**
- If you are running the compiled binary from `cygwin` cli, input file list won't work, there will be error on resolving full path from `realpath()`, but will work if you run it from regular `cmd`.
- If you are running the compiled binary from regular `cmd`, wildcard on file path other than your current working directory won't work. Same error from `realpath()`
- To be able to run it from `cmd`, you have to provide `cygwin1.dll` along with the compiled binary or add it to your system path.

**Windows Subsytem for Linux**
- The file path stored on the database will obviously be in unix-style path.

**Comment by chad-earthscope** [comment]
Excellent, thanks for sharing your experience!

**Comment by adienakhmad** [comment]
You're welcome chad, thanks for developing this tool, the combination of `timeindex` and `timespans` is indeed very useful.
